spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liberary
    username: postgres

    password: root

    driver-class-name: org.postgresql.Driver

  jpa.hibernate.ddl-auto: create
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
